Improvement subject area rest resources
odpi/egeria pull request #3524
Opened 2020-08-25 22:00 UTC by immmus

I added request methods for getGlossaryCategories, getGlossaryTerms, getCategoryTerms.

2020-08-25 22:55 UTC, planetf1 commented
The grade build is failing after the version bump. It is not due to this pr. I have now disabled the mandatory nature of the check and will look at resolving. . The best push or update should be fine. Apologies

2020-08-27 14:10 UTC, davidradl commented
@immmus I hope to review this tomorrow

2020-08-28 09:20 UTC, davidradl requested changes
I assume you are looking to do the Client library, FVT and the glossary author View services changes for these APIs in a separate issue.
I have raised the issue that there are no paging options, It would make sense to add paging options to all the get relationship methods.

2020-08-28 09:20 UTC, davidradl commented on open-metadata-implementation/access-services/subject-area/subject-area-server/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/handlers/SubjectAreaGlossaryHandler.java
> +     * Get Glossary terms
I suggest the description and method name be enhanced to say -get glossary terms for this category

2020-08-28 09:20 UTC, davidradl commented on open-metadata-implementation/access-services/subject-area/subject-area-server/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/handlers/SubjectAreaGlossaryHandler.java
> +    public SubjectAreaOMASAPIResponse<Term> getGlossaryTerms(String userId, String guid) {
This method (and all the other get relationship APs you have added) should have paging options. I notice that the existing get relationships do not have the paging options - I would prefer new APIs to be added with paging , you could fix the existing get relationship APIs to add paging here as well if you like.

2020-08-28 09:20 UTC, davidradl commented on open-metadata-implementation/access-services/subject-area/subject-area-server/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/server/services/SubjectAreaCategoryRESTServices.java
> +     * Get Category terms
This should have a description. Get the terms that are categorized by this Category.

2020-08-28 09:20 UTC, davidradl commented on open-metadata-implementation/access-services/subject-area/subject-area-server/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/handlers/SubjectAreaGlossaryHandler.java
> +     * Get Glossary categories
Needs a description.Get the Categories owned by this glossary.

2020-08-28 09:20 UTC, davidradl commented on open-metadata-implementation/access-services/subject-area/subject-area-server/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/server/services/SubjectAreaGlossaryRESTServices.java
> +    public SubjectAreaOMASAPIResponse<Term> getGlossaryTerms(String serverName, String userId, String guid) {
Needs paging options - this call particularly is exposed here as there could be 1000s of terms in a large Glossary

2020-08-28 09:20 UTC, davidradl commented on open-metadata-implementation/access-services/subject-area/subject-area-server/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/server/services/SubjectAreaGlossaryRESTServices.java
> +     * Get Glossary terms
get terms that are owned by this glossary

2020-08-28 09:20 UTC, davidradl commented on open-metadata-implementation/access-services/subject-area/subject-area-spring/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/server/spring/SubjectAreaCategoryRESTResource.java
> +    public SubjectAreaOMASAPIResponse<Term> getCategoryTerms(@PathVariable String serverName,
I think it would be clearer to rename to getCategorizedTerms

2020-08-28 09:20 UTC, davidradl commented on open-metadata-implementation/access-services/subject-area/subject-area-spring/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/server/spring/SubjectAreaGlossaryRESTResource.java
> +     * @return A list of terms for the glossary
owned by the glossary

2020-08-28 09:25 UTC, immmus commented
> I assume you are looking to do the Client library, FVT and the glossary author View services changes for these APIs in a separate issue.
> I have raised the issue that there are no paging options, It would make sense to add paging options to all the get relationship methods.

I can add the Client library and FVT to this pr after review API. Okay?

2020-09-02 08:07 UTC, davidradl commented
> I can add the Client library and FVT to this pr after review API. Okay?
@immmus Yes of course

2020-09-02 09:50 UTC, immmus commented on open-metadata-implementation/access-services/subject-area/subject-area-spring/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/server/spring/SubjectAreaGlossaryRESTResource.java
> +     * @return A list of terms for the glossary
+

2020-09-02 09:51 UTC, immmus commented
@davidradl javadocs changed

2020-09-04 09:35 UTC, davidradl requested changes
I do not think that we should add new APIs, when we know they should have paging. I think the paging options should be added in this pr, so that we do not have 2 versions of the API in the code base, one with and one without paging.

2020-09-04 09:35 UTC, davidradl commented on open-metadata-implementation/access-services/subject-area/subject-area-server/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/handlers/SubjectAreaCategoryHandler.java
> +     * @return A list of terms is categorized by this Category
A list of terms that are categorized by this Category.

2020-09-04 09:35 UTC, davidradl commented on open-metadata-implementation/access-services/subject-area/subject-area-server/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/server/services/SubjectAreaCategoryRESTServices.java
> +     * @return A list of terms is categorized by this Category
A list of terms that are categorized by this Category

2020-09-04 09:39 UTC, immmus commented
> I do not think that we should add new APIs, when we know they should have paging. I think the paging options should be added in this pr, so that we do not have 2 versions of the API in the code base, one with and one without paging.

Yes I  am work about it

2020-10-08 08:38 UTC, davidradl commented
> @davidradl I am wait this merge pr #3493

Hi @immmus, I am wondering when you are thinking of getting to this. If you are not likely to get to this soon - I could finish this for you.

2020-10-08 15:53 UTC, immmus commented
> > @davidradl I am wait this merge pr #3493
> 
> Hi @immmus, I am wondering when you are thinking of getting to this. If you are not likely to get to this soon - I could finish this for you.

Hi! Yes) I unfortunately very busy now...

2020-10-12 12:40 UTC, davidradl commented
@immmus OK I am taking over this pr .

2020-10-13 11:04 UTC, davidradl commented
@immmus Trying to develop on this pr hasled to my ide becoming corrupted - which took hours to recover. I am going to do this in another pr.

2020-10-16 13:27 UTC, davidradl commented
I am using this issue to extend the existing APIs to allow objects to see their "children" or "parents", this includes
- terms to return their categorizing categories
- glossaries to return their categories, with a flag to return only categories without parents. 
- glossaries to return their terms  
- categories to return their children categories
- projects to return their terms.
- categories to return their terms 
The above APIs return multiple artifacts, so these APS need to be paged. Paging in the subject area was incorrectly implemented, it should not be hard coded, server side is should pick up the configured server maxPagesize in the absence of a page size being requested. 
Also the InvalidParameterHandler already has standard logic for validating page sizes, this can be used client side and server side. I propose to use this checking. 
This means page size could be null meaning pick up the default ( from the server config)
The date was being serialised as a Date object - this can be problematic - I have changed the subject areas Dates to be longs - so they serialise more simply.         

I have extended these APIs to the client and added FVTs to test them. I have also added view services for them

2020-10-19 10:51 UTC, davidradl commented
I have created another pr to address this issue - which should address the review comments. https://github.com/odpi/egeria/pull/3906

2020-10-19 10:51 UTC, closed without merging