#4252 ensure surefire always triggers in test phase for all modules
odpi/egeria pull request #4264
Opened 2020-12-03 13:24 UTC by planetf1

Signed-off-by: Nigel Jones <nigel.l.jones+git@gmail.com>

Fixes #4252 

 - Adds surefire as a default build plugin for all modules
 - surefire is intelligent enough to skip pom modules & others without tests

2020-12-08 18:59 UTC, planetf1 commented
Fixed some of the duplicationsin repository services ... more to follow (which is why test currently still failing)

2020-12-09 11:02 UTC, planetf1 commented
@mandy-chessell Errors are unique (there were A LOT). I'm not convinced my wording is great, so any review welcome.
However, they are now all unique and pass the unit test correctly, which is invoked via maven (I will look at gradle as part of the gradle thread - need to check cross-tool consistency)

2020-12-09 12:14 UTC, planetf1 commented
The repository services UTs are fixed (de-duplicated). However this PR now fails with:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project ui-chassis-spring: There are test failures.
```

2020-12-09 13:00 UTC, planetf1 commented
@bogdan @sarbull - Note the disabling of the spring ui chassis tests. In fact they were never running  it would seem (just like Mandy's test). I opened up the referenced issue to track fixing them (and reenabling them) and assigned to you. Hope that works.

2020-12-10 17:40 UTC, planetf1 commented
Note #4294 adds fixes for the UI UT's . I would be desirable to get this change in first. I suggest merging this tomorrow (and raise a new PR if further changes needed to message texts)

2020-12-11 08:01 UTC, bogdan-sava requested changes

2020-12-11 08:01 UTC, bogdan-sava commented on pom.xml
> +                <version>2.22.1</version>
overriding version from main pom.xml ?

2020-12-11 08:46 UTC, planetf1 commented on open-metadata-implementation/user-interfaces/ui-chassis/ui-chassis-spring/pom.xml
> +            <version>4.13.1</version>
Thanks - removed.. though there is another issue open to correct the ui tests. But in any case this is against our strategy of keeping versions in dependencyManagement so thanks for the spot!

2020-12-11 08:48 UTC, planetf1 commented on pom.xml
> +                <version>2.22.1</version>
Good spot. Bad cut/paste on my behalf. Thanks. Fixed

2020-12-11 09:50 UTC, planetf1 commented
@bogdan I found a few others so updated there also -- we still have a couple
 - for gaian/ranger plugin - these are moving to new repo anyway
 - specific dependencies of plugins where dependencyManagement didn't seem to work (like groovy for fvt)

These I'm sure can be improved in future

but I removed some additional obvious ones ie for jupiter api which were unnecessary.

2020-12-11 09:59 UTC, planetf1 commented
@bogdan-sava I think I've answered your questions. I'm planning to merge this shortly so that we can improve the testing integrity

2020-12-11 10:12 UTC, merged