Update egeria-dojo-day-1-4-participating-in-the-community.md
odpi/egeria pull request #4738
Opened 2021-02-26 15:31 UTC by lpalashevski

As reported by user on Slack looks like the "Code of conduct" link pointing to the .md file does show the page (suspect because of the different naming convention and internals of how it is translated to html..). Updating the link to the actual github location like it is already in the other dojo pages.

2021-02-28 16:34 UTC, mandy-chessell requested changes
The fix is pointing to the wrong file - It need to point to the CODE_OF_CONDUCT.md file in the egeria git repository - not the ODPi specs.

2021-02-28 16:39 UTC, mandy-chessell commented
It looks like the link in the CODE_OF_CONDUCT.md file need to be turned into a clickable link

2021-03-01 11:57 UTC, lpalashevski commented
maybe we need to do the same for other website md files referencing code of conduct:

Community-Guide.md
Egeria-Operations.md
index.md

README.md (?)
CONTRIBUTING.md (?)

looks like CODE_OF_CONDUCT.md file is not following the same .md->.html pattern like the rest of the files. Not sure if this is some configuration with github pages/jekyll or we  need to rebuild the site but might be because of the different naming convention. Lets dicuss it first.


cc: @planetf1

2021-03-03 12:16 UTC, planetf1 commented
It may be worth checking our other repos also (perhaps the most viable is to ensure they link back to the content in egeria where possible)

I am only aware of the _config.yml & haven't done any other work with github pages configuration.

From https://nicolas-van.github.io/easy-markdown-to-github-pages/ I see
 - It does confirm just replacing .md with .html should work (which is what the original document does)
  - The example above does explicitly list the additional .md files - I'm not sure what the default pattern is. 
  
I can only suggest some experimenting and research is needed.

2021-03-03 12:17 UTC, planetf1 requested changes
see comment added previously

2021-03-03 12:34 UTC, mandy-chessell commented
Replacing html with md will create a broken link in github and intelliJ

2021-03-03 12:48 UTC, lpalashevski commented
Based on Nigels' input I would suggest to try explicitly including the .md files we have in the root of the repo in _config.yml and see if it generates missing pages. We can also try only with CODE_OF_CONDUCT.md but I am afraid that it might break the site (if in case it forces only included files).

```
include:
  - index.md
  - CODE_OF_CONDUCT.md
  - CodeQualitySecurity.md
  - Community-Guide.md
  - Content-Organization.md
  - CONTRIBUTING.md
  - CONTRIBUTORS.md
  - Egeria-Operations.md
  - GOVERNANCE.md
  - MAINTAINERS.md
  - README.md
 ```

2021-03-08 10:33 UTC, planetf1 commented
I think there are more fixes needed to address the root issue so suggesting we have this only as draft to reduce chance of breakage

2021-05-28 00:36 UTC, closed without merging