#4727 fix up the view server postman collection
odpi/egeria pull request #4739
Opened 2021-02-26 15:45 UTC by davidradl

2021-02-26 15:57 UTC, wbittles approved these changes

2021-02-26 16:49 UTC, planetf1 requested changes
I think this collection needs to use variables from the environment, just changing the name is 
a marginal improvement, but we should be consistent with the other collections?

Great to have a collection for the view server though :-)

2021-02-26 16:49 UTC, planetf1 commented on open-metadata-implementation/admin-services/Egeria-admin-services-server-configuration.postman_collection.json
> +									"raw": "      { \n         \"class\":\"ViewServiceConfig\",\n         \"omagserverName\":\"myMetadataAccessPoint\",\n         \"omagserverPlatformRootURL\":\"myPlatformRootURL1\"\n      }"
This should be using postman variables from your environment definition ie  {{platformURL}} {{serverName}} etc
Use the variables defined in the current env files & extend with any new concepts like view servers etc - that way someone just needs to update their environment definition, not edit the actual collection?

2021-02-26 16:49 UTC, planetf1 commented on open-metadata-implementation/admin-services/Egeria-admin-services-server-configuration.postman_collection.json
> +									"raw": "{\n    \"class\":\"IntegrationViewServiceConfig\",\n    \"viewServiceAdminClass\":\"org.odpi.openmetadata.viewservices.rex.admin.RexViewAdmin\",\n    \"viewServiceFullName\":\"Reposi
should also use variables

2021-02-26 16:49 UTC, planetf1 commented on open-metadata-implementation/admin-services/Egeria-admin-services-server-configuration.postman_collection.json
> +									"raw": "{\n    \"class\":\"IntegrationViewServiceConfig\",\n    \"viewServiceAdminClass\":\"org.odpi.openmetadata.viewservices.rex.admin.TexViewAdmin\",\n    \"viewServiceFullName\":\"TypeEx
variables...

2021-02-26 16:49 UTC, planetf1 commented on open-metadata-implementation/admin-services/Egeria-admin-services-server-configuration.postman_collection.json
> +									"raw": "{\n    \"class\":\"IntegrationViewServiceConfig\",\n    \"viewServiceAdminClass\":\"org.odpi.openmetadata.viewservices.serverauthor.admin.ServerAuthorViewAdmin\",\n    \"viewFullServ
variables

2021-02-26 16:49 UTC, planetf1 commented on open-metadata-implementation/admin-services/Egeria-admin-services-server-configuration.postman_collection.json
> +									"raw": "{\n    \"class\":\"IntegrationViewServiceConfig\",\n    \"viewServiceAdminClass\":\"org.odpi.openmetadata.viewservices.dino.admin.DinoViewAdmin\",\n    \"viewServiceFullName\":\"Dino
variables

2021-03-01 17:35 UTC, planetf1 commented
The PR now seems to be checking correctly - backlog now mostly addressed

2021-03-01 18:26 UTC, merged