Add Alexandra Bucur and Cezar Sirbu to maintainers
odpi/egeria pull request #4864
Opened 2021-03-05 11:15 UTC by bogdan-sava

Signed-off-by: Bogdan Sava <bogdan.sava@gmail.com>

2021-03-08 10:18 UTC, planetf1 requested changes
The file change is good.
I have invited @sarbull to the contributor team on github.
However I am not able to add @alexandra-bucur to the //organization// as I don't have permissions - @mandy-chessell @jmertic would you be able to do this please?
(then will merge so we know everything is done)

2021-03-08 14:12 UTC, mstrelchuk commented
Hi Nigel,
Alexandra was successfully added to Egeria Maintainers list.

2021-03-09 07:03 UTC, planetf1 commented
> Hi Nigel,
> Alexandra was successfully added to Egeria Maintainers list.

Thanks. can merge now

2021-03-09 07:03 UTC, planetf1 approved these changes

2021-03-09 07:33 UTC, merged