Add primary category type
odpi/egeria pull request #5054
Opened 2021-04-12 10:44 UTC by marius-patrascu

2021-04-20 10:35 UTC, mandy-chessell reviewed
The images should have a border of 5, and shadow and transparency set,

2021-04-20 10:35 UTC, mandy-chessell commented on open-metadata-publication/website/open-metadata-types/0335-Primary-Category.md
> +It contains a single filed, `categoryQualifiedName` which represents the qualified name of the primary category associated with the term.
Spelling mistake in filed - should be property.

2021-04-20 10:35 UTC, mandy-chessell commented on open-metadata-publication/website/open-metadata-types/0335-Primary-Category.md
> +It contains a single filed, `categoryQualifiedName` which represents the qualified name of the primary category associated with the term.
Add link to category

2021-04-20 10:35 UTC, mandy-chessell commented on open-metadata-resources/open-metadata-archives/open-metadata-types/src/main/java/org/odpi/openmetadata/opentypes/OpenMetadataTypesArchive.java
> +        OpenMetadataTypesArchive2_9  previousTypes = new OpenMetadataTypesArchive2_9(archiveBuilder);
should be 2_8

2021-04-20 10:35 UTC, mandy-chessell commented on open-metadata-resources/open-metadata-archives/open-metadata-types/src/main/java/org/odpi/openmetadata/opentypes/OpenMetadataTypesArchive2_9.java
> +/* SPDX-License-Identifier: Apache-2.0 */
The new type definition should go in file OpenMetadataTypesArchive.java

2021-04-20 10:35 UTC, mandy-chessell commented on open-metadata-resources/open-metadata-archives/open-metadata-types/src/main/java/org/odpi/openmetadata/opentypes/OpenMetadataTypesArchive2_9.java
> +        final String name            = "PrimaryCategoryClassification";
Do not need the word Classification in the title - it should be "PrimaryClassification"

2021-04-20 10:37 UTC, mandy-chessell requested changes
The new type definition needs to be moved to OpenMetadataTypesArchive.java before merging

2021-04-20 10:42 UTC, mandy-chessell commented
The image for https://github.com/odpi/egeria/blob/ed0f2a81dd5cf736fe631d9e54c08bfcf507ca7d/open-metadata-publication/website/open-metadata-types/0335-Primary-Category.png

* has a spelling mistake in - PrimaryCategory
* Has the wrong sized box around it - it should be the same size as the other pages.

2021-04-21 16:31 UTC, lpalashevski approved these changes
looks good. @mandy-chessell can you please take a look and approve?

2021-04-22 09:52 UTC, cmgrote approved these changes

2021-04-23 11:25 UTC, mandy-chessell reviewed
The area-3-glossary-overview.png is missing the shadow.

2021-04-23 11:25 UTC, mandy-chessell commented on open-metadata-resources/open-metadata-archives/open-metadata-types/src/main/java/org/odpi/openmetadata/opentypes/OpenMetadataTypesArchive.java
> +                attribute1Description,
Code layout issue - need to align parametersunder attribute1Name

2021-04-23 11:27 UTC, mandy-chessell approved these changes

2021-04-23 11:27 UTC, mandy-chessell commented
There are a coupld of minor issues still to resolve - however can be done in a separate PR

2021-04-23 11:27 UTC, merged