add audit logging when kafka connection fails to initialise
odpi/egeria pull request #5242
Opened 2021-05-28 14:42 UTC by wbittles

fix for #5028
Signed-off-by: William Bittles <wbittles@uk.ibm.com>

2021-05-28 15:44 UTC, mandy-chessell requested changes

2021-05-28 15:44 UTC, mandy-chessell commented on open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataTopicConnectorAuditCode.java
> +            " Egeria has encountered an unrecoverable error while attempting to send messages to the following topic {0}",
Specify specific component that is failing - "egeria" is too generic.  My guess is that it should be something like the KafkaOpenMetadataTopicConnector.  Detail the class of exception and any message within it.

2021-05-28 15:44 UTC, mandy-chessell commented on open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataTopicConnectorAuditCode.java
> +            "Ensure that the kakfa service is available",
The system response should describe the state of the server as a result of the failure - is it going to retry this event? shutdown? try to send the next message?

2021-05-28 15:44 UTC, mandy-chessell commented on open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataTopicConnectorAuditCode.java
> +            "Ensure that the kafka service is available"),
For the user action, do they need to do anything to server to restart sends once Kafka is available?

2021-05-28 15:44 UTC, mandy-chessell commented on open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataTopicConnectorAuditCode.java
> -
Why has this whitespace been removed throughout the file?

2021-05-29 10:28 UTC, wbittles commented
Need to go back to the issue , not sure this fix is correct

2021-05-29 10:28 UTC, closed without merging