add check to update unknown artifact.
odpi/egeria pull request #5470
Opened 2021-07-08 02:40 UTC by yevgenmar

Signed-off-by: Yevgeniy Marchenko <yevgeniy.marchenko@ca.ibm.com>

2021-07-08 17:11 UTC, planetf1 requested changes

2021-07-08 17:11 UTC, planetf1 commented on open-metadata-implementation/access-services/analytics-modeling/analytics-modeling-api/src/main/java/org/odpi/openmetadata/accessservices/analyticsmodeling/ffdc/AnalyticsModelingErrorCode.java
> +			"Confirm the arifact exists."),
arifact -> artifact (typo)

2021-07-08 17:49 UTC, yevgenmar commented on open-metadata-implementation/access-services/analytics-modeling/analytics-modeling-api/src/main/java/org/odpi/openmetadata/accessservices/analyticsmodeling/ffdc/AnalyticsModelingErrorCode.java
> +			"Confirm the arifact exists."),
fixed

2021-07-09 07:33 UTC, planetf1 approved these changes

2021-07-09 07:34 UTC, merged