fix maven dependencies version
odpi/egeria pull request #5930
Opened 2021-11-15 20:05 UTC by bogdan-sava

# Description

server-chassis-spring is not working started in IntelliJ by adding intellij runtime dependency.
 
:graph-repository-connector brings `:hibernate-validator:4.2.0` via `:janusgraph-cql`  -> `:cassandra-all` -> `:reporter-config3`
This version of hibernate-validator is not compatible with spring-boot

Fixed by controlling hibernate-validator version through dependency management

2021-11-16 09:26 UTC, lpalashevski approved these changes

2021-11-16 11:11 UTC, planetf1 requested changes
@bogdan-sava Can you describe the scenario to demonstrate the original problem - is there a linked issue?

Here I see we are:
 * Adding a new dependency for the graph repo connector (scope=compile)
 * Adding an exception for our dependency checker (which normally is only needed for scope=runtime)
  * Adding spring-boot-starter-validation to server chassis & ui chassis (with exception, but this is normal for spring boot as it's typically runtime)
  
 This has resulted in needing the older hibernate version -- if we have to go with it that's fine - though we should check for outstanding CVEs. But I'd like to also understand the mechanics as I believe the code works as-is with maven, but the problem you are addressing only manifests itself in the intelliJ environment
  
 I understand there was an initial loading issue - am I correct that all the above changes were specifically to address this? Is there a reason the ui-chassis is affected since it does not load connectors?

2021-11-16 14:03 UTC, bogdan-sava commented
The issue is that while configure IntelliJ with additional maven dependency for running server-chassis-spring with graph-repository-connector, fails with: 
```

 Project Egeria - Open Metadata and Governance
    ____   __  ___ ___    ______   _____                                 ____   _         _     ___
   / __ \ /  |/  //   |  / ____/  / ___/ ___   ____ _   __ ___   ____   / _  \ / / __    / /  / _ /__   ____ _  _
  / / / // /|_/ // /| | / / __    \__ \ / _ \ / __/| | / // _ \ / __/  / /_/ // //   |  / _\ / /_ /  | /  _// || |
 / /_/ // /  / // ___ |/ /_/ /   ___/ //  __// /   | |/ //  __// /    /  __ // // /  \ / /_ /  _// / // /  / / / /
 \____//_/  /_//_/  |_|\____/   /____/ \___//_/    |___/ \___//_/    /_/    /_/ \__/\//___//_/   \__//_/  /_/ /_/

 :: Powered by Spring Boot (v2.5.6) ::

2021-11-16 15:58:10.424  INFO 76913 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9443 (https)
2021-11-16 15:58:12.500 ERROR 76913 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultValidator' defined in class path resource [org/springframework/boot/autoconfigure/validation/ValidationAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.AbstractMethodError: Receiver class org.hibernate.validator.internal.engine.ConfigurationImpl does not define or inherit an implementation of the resolved method 'abstract javax.validation.ParameterNameProvider getDefaultParameterNameProvider()' of interface javax.validation.Configuration.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.12.jar:5.3.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.12.jar:5.3.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.12.jar:5.3.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.12.jar:5.3.12]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.12.jar:5.3.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.12.jar:5.3.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.12.jar:5.3.12]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.12.jar:5.3.12]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.6.jar:2.5.6]
	at org.odpi.openmetadata.serverchassis.springboot.OMAGServerPlatform.main(OMAGServerPlatform.java:95) ~[classes/:na]
Caused by: java.lang.AbstractMethodError: Receiver class org.hibernate.validator.internal.engine.ConfigurationImpl does not define or inherit an implementation of the resolved method 'abstract javax.validation.ParameterNameProvider getDefaultParameterNameProvider()' of interface javax.validation.Configuration.
	at org.springframework.validation.beanvalidation.LocalValidatorFactoryBean.configureParameterNameProvider(LocalValidatorFactoryBean.java:327) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.validation.beanvalidation.LocalValidatorFactoryBean.afterPropertiesSet(LocalValidatorFactoryBean.java:293) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.12.jar:5.3.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.12.jar:5.3.12]
	... 16 common frames omitted

Disconnected from the target VM, address: '127.0.0.1:57823', transport: 'socket'

Process finished with exit code 1
```

Main problem is that `Receiver class org.hibernate.validator.internal.engine.ConfigurationImpl does not define or inherit an implementation of the resolved method 'abstract javax.validation.ParameterNameProvider getDefaultParameterNameProvider()`

2021-11-16 14:12 UTC, bogdan-sava commented
This is happening because IntelliJ is running the OMAGServerPlatform main class with the following command:

```
java 
-agentlib:jdwp=transport=dt_socket,address=127.0.0.1:57823,suspend=y,server=n
-javaagent:/Users/bogdans/Library/Caches/JetBrains/IdeaIC2021.2/groovyHotSwap/gragent.jar
-javaagent:/Users/bogdans/Library/Caches/JetBrains/IdeaIC2021.2/captureAgent/debugger-agent.jar
-Dfile.encoding=UTF-8
-classpath /Users/bogdans/Projects/egeria-b/open-metadata-implementation/server-chassis/server-chassis-spring/target/classes:/Users/bogdans/.m2/repository/org/springframework/boot/spring-boot/2.5.6/spring-boot-2.5.6.jar:/Users/bogdans/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.5.6/spring-boot-autoconfigure-2.5.6.jar:/Users/bogdans/.m2/repository/org/springframework/boot/spring-boot-starter-actuator/2.5.6/spring-boot-starter-actuator-2.5.6.jar:/Users/bogdans/.m2/repository/org/springframework/boot/spring-boot-starter/2.5.6/spring-boot-starter-2.5.6.jar:/Users/bogdans/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.5.6/spring-boot-starter-logging-2.5.6.jar:/Users/bogdans/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.14.1/log4j-to-slf4j-2.14.1.jar:/Users/bogdans/.m2/repository/org/slf4j/jul-to-slf4j/1.7.32/jul-to-slf4j-1.7.32.jar:/Users/bogdans/.m2/repository/org/yaml/snakeyaml/1.29/snakeyaml-1.29.jar:/Users/bogdans/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/2.5.6/spring-boot-actuator-autoconfigure-2.5.6.jar:/Users/bogdans/.m2/repository/org/springframework/boot/spring-boot-actuator/2.5.6/spring-boot-actuator-2.5.6.jar:/Users/bogdans/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.13.0/jackson-datatype-jsr310-2.13.0.jar:/Users/bogdans/.m2/repository/io/micrometer/micrometer-core/1.7.5/micrometer-core-1.7.5.jar:/Users/bogdans/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.12/HdrHistogram-2.1.12.jar:/Users/bogdans/.m2/repository/org/latencyutils/LatencyUtils/2.0.3/LatencyUtils-2.0.3.jar:/Users/bogdans/.m2/repository/io/micrometer/micrometer-registry-prometheus/1.7.5/micrometer-registry-prometheus-1.7.5.jar:/Users/bogdans/.m2/repository/io/prometheus/simpleclient_common/0.10.0/simpleclient_common-0.10.0.jar:/Users/bogdans/.m2/repository/io/prometheus/simpleclient/0.10.0/simpleclient-0.10.0.jar:/Users/bogdans/.m2/repository/org/springframework/spring-beans/5.3.12/spring-beans-5.3.12.jar:/Users/bogdans/.m2/repository/org/springframework/spring-context/5.3.12/spring-context-5.3.12.jar:/Users/bogdans/.m2/repository/org/springframework/spring-aop/5.3.12/spring-aop-5.3.12.jar:/Users/bogdans/.m2/repository/org/springframework/spring-expression/5.3.12/spring-expression-5.3.12.jar:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/platform-services/platform-services-spring/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/platform-services/platform-services-server/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/platform-services/platform-services-api/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/common-services/ffdc-services/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/adapters/open-connectors/rest-client-connectors/rest-client-connectors-api/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/adapters/open-connectors/rest-client-connectors/rest-client-factory/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/adapters/open-connectors/rest-client-connectors/spring-rest-client-connector/target/classes:/Users/bogdans/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:/Users/bogdans/.m2/repository/org/springframework/spring-web/5.3.12/spring-web-5.3.12.jar:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/integration-services/search-integrator/search-integrator-api/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/frameworks/audit-log-framework/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/frameworks/open-connector-framework/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/governance-servers/integration-daemon-services/integration-daemon-services-api/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/repository-services/repository-services-apis/target/classes:/Users/bogdans/.m2/repository/org/apache/commons/commons-collections4/4.4/commons-collections4-4.4.jar:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/access-services/asset-catalog/asset-catalog-client/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/common-services/ocf-metadata-management/ocf-metadata-client/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/access-services/asset-catalog/asset-catalog-api/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/integration-services/search-integrator/search-integrator-spring/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/integration-services/search-integrator/search-integrator-server/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/access-services/asset-manager/asset-manager-client/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/integration-services/search-integrator/search-integrator-client/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/admin-services/admin-services-spring/target/classes:/Users/bogdans/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/admin-services/admin-services-server/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/admin-services/admin-services-registration/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/common-services/multi-tenant/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/common-services/repository-handler/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/common-services/metadata-security/metadata-security-server/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/common-services/metadata-security/metadata-security-apis/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/common-services/metadata-security/metadata-security-connectors/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/adapters/open-connectors/connector-configuration-factory/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/audit-log-connectors/audit-log-file-connector/target/classes:/Users/bogdans/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/audit-log-connectors/audit-log-console-connector/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/audit-log-connectors/audit-log-slf4j-connector/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/audit-log-connectors/audit-log-event-topic-connector/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/cohort-registry-store-connectors/cohort-registry-file-store-connector/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/open-metadata-collection-store-connectors/inmemory-repository-connector/target/classes:/Users/bogdans/Projects/egeria-b/open-metadata-implementation/adapters/open-connec [...]

2021-11-16 14:25 UTC, bogdan-sava commented
The dependency can be runtime. Is it help with check?
Otherwise the only difference between compile and runtime is that runtime is not present in classpath during compilation. Both are propagated to the dependent projects.
Only 'provided' is not propagated to dependent projects.

2021-11-17 15:11 UTC, davidradl commented
@bogdan-sava @planetf1 I wondered whether an equivalent change needs to be made to gradle or is this not an issue for the gradle build?

2021-11-18 08:54 UTC, lpalashevski commented
I am proposing to continue the discussion and the review on the security call and see if there is need to threat some  aspects proposed by this change separately.

2021-11-18 09:42 UTC, planetf1 approved these changes
I approve and recommend merging :
* you’ve done investigation of a specific problem with the connector and also looked at the general way things work
* It addresses a real problem for you & the team
* There is a PR ready to go
* I’ve not identified a specific issue during the review - just a feeling of some oddities in IntelliJ/mvn but which could be my understanding. I don’t have any evidence of a problem written up (other than a minor backleveling)
* even if there were to be issues, this doesn't make things any worse.
* There is no justification for further delay.
* Therefore we merge.
* Then, let’s see how it goes.. we still have a week or two in the release. More people will have exposure.

If/when I can document a clear broken path (there may not be one …) I will raise a new issue and we’ll take it from there based on that specific evidence 

Approve.

2021-11-18 09:47 UTC, planetf1 commented
@davidradl ideally we should get gradle to parity - but the gradle build still needs a concerted effort to get to parity.
https://github.com/odpi/egeria/issues/3370 has some of the remaining work - maybe it's best we add this as a note to it, since we (I for sure) haven't yet validated any of the dependency resolution in detail. That task is listed. We do the best we can to stop things regression, but I think this area is beyond that (but important). So I would not hold up the PR for gradle in this particular case - just refer to #3370 ?

2021-11-18 10:16 UTC, merged