#6022 Fix the metadataCollection.addTypeDef logic in OMRSRepositoryContentManager.processNewTypeDefEvent
odpi/egeria pull request #6024
Opened 2021-12-08 11:36 UTC by gnahZ-eH

#6022 Fix the metadataCollection.addTypeDef logic in OMRSRepositoryContentManager.processNewTypeDefEvent.

# Description

In the class OMRSRepositoryContentManager, here are two methods: processNewAttributeTypeDefEvent and processNewTypeDefEvent.

I believe that these two methods are similar, one will handle the EntityTypeDef, another will handle AttributeTypeDef.
You can see two lines codes from these two methods: line 2866, and 2677
I believe that the line 2677 in processNewTypeDefEvent
```java
metadataCollection.addTypeDef(sourceName, typeDef);
```
the parameter **sourceName** should be changed to **localServerUserId**, just like line 2866 in processNewAttributeTypeDefEvent

Fixes #6022 

# How Has This Been Tested?

Yes have tested from my side. 

# Any additional notes for reviewers?

2021-12-09 08:49 UTC, mandy-chessell requested changes

2021-12-09 08:49 UTC, mandy-chessell commented on open-metadata-implementation/repository-services/repository-services-implementation/src/main/java/org/odpi/openmetadata/repositoryservices/localrepository/repositorycontentmanager/OMRSRepositoryContentManager.java
> +                    if (!metadataCollection.verifyTypeDef(localServerUserId, typeDef))
Please add the space back in....

2021-12-09 08:59 UTC, gnahZ-eH commented on open-metadata-implementation/repository-services/repository-services-implementation/src/main/java/org/odpi/openmetadata/repositoryservices/localrepository/repositorycontentmanager/OMRSRepositoryContentManager.java
> +                    if (!metadataCollection.verifyTypeDef(localServerUserId, typeDef))
Done.

2021-12-10 09:21 UTC, mandy-chessell approved these changes

2021-12-10 10:05 UTC, merged