AI OMAS - build context for Topics & EventSchemaAttribute
odpi/egeria pull request #6056
Opened 2021-12-29 10:03 UTC by popa-raluca

# Description

Enhance the context for Topic & EventSchemaAttribute with specific structure

Fixes # (issue)

# How Has This Been Tested?

Tested locally and with unit tests
# Any additional notes for reviewers?

2021-12-29 16:08 UTC, lpalashevski approved these changes

2022-01-14 11:04 UTC, lcpopa approved these changes

2022-01-26 12:25 UTC, marius-patrascu commented on open-metadata-implementation/adapters/open-connectors/governance-daemon-connectors/open-lineage-connectors/open-lineage-janus-connector/src/main/java/org/odpi/openmetadata/openconnectors/governancedaemonconnectors/openlineageconnectors/janusconnector/graph/LineageGraphConnectorHelper.java
> +        lineageVertices.forEach(lineageVertex -> {
this check should be kept for ultimate source/ ultimate destination nodes or a special checks for those types of nodes.

2022-01-26 12:27 UTC, marius-patrascu requested changes

2022-01-26 12:27 UTC, marius-patrascu commented on open-metadata-implementation/adapters/open-connectors/governance-daemon-connectors/open-lineage-connectors/open-lineage-janus-connector/src/main/java/org/odpi/openmetadata/openconnectors/governancedaemonconnectors/openlineageconnectors/janusconnector/graph/LineageGraphConnectorHelper.java
> +        lineageVertices.forEach(lineageVertex -> {
this check should be kept for ultimate source/ ultimate destination nodes or a special check for those types of nodes.

2022-01-27 09:48 UTC, marius-patrascu approved these changes

2022-01-27 10:22 UTC, merged