DE - Refactor remaining classes to use generic handlers
odpi/egeria pull request #6519
Opened 2022-05-06 07:38 UTC by alexandra-bucur

Signed-off-by: Alexandra Bucur <alexandra-nona.bucur@ing.com>

A few Data Engine handlers still used the repository handler instead of the generic handlers - OpenMetadataAPIGenericHandler, so a refactoring was needed. 

## Description

- refactored DE handlers
- removed unused methods from RepositoryHandler

## Testing

JUnits, manual, FVT

2022-05-06 10:10 UTC, lcpopa requested changes

2022-05-06 10:10 UTC, lcpopa commented on open-metadata-implementation/access-services/data-engine/data-engine-server/src/main/java/org/odpi/openmetadata/accessservices/dataengine/server/handlers/DataEngineCommonHandler.java
> +    public Optional<EntityDetail> getEntityDetails(String userId, String entityDetailGUID, String entityTypeGUID,
Git warning: The parameter entityTypeGUID is unused

2022-05-06 10:10 UTC, lcpopa commented on open-metadata-implementation/access-services/data-engine/data-engine-server/src/main/java/org/odpi/openmetadata/accessservices/dataengine/server/handlers/DataEngineCommonHandler.java
> +            String relationshipGUID = genericHandler.linkElementToElement(userId, externalSourceGUID, externalSourceName, firstGUID,
relationshipGUID is never used also. Not assigning the returned value of linkElementToElement should fix it

2022-05-11 17:42 UTC, planetf1 commented
I noticed the DCO check is 'stuck'. I suspect it will be ok once the branch is updated.

2022-05-12 06:55 UTC, alexandra-bucur commented
@planetf1 thank you! it worked at the rerun.

2022-06-14 09:22 UTC, alexandra-bucur commented on open-metadata-implementation/access-services/data-engine/data-engine-server/src/main/java/org/odpi/openmetadata/accessservices/dataengine/server/handlers/DataEngineCommonHandler.java
>      private final String serviceName;
Common pattern to use the service name information in access services. This needs to be refactored in order to be used. Won't fix this for the moment.

2022-06-16 12:11 UTC, lcpopa approved these changes

2022-06-16 12:37 UTC, merged