AC, AL - Change effectivity dates to now
odpi/egeria pull request #6811
Opened 2022-08-17 08:30 UTC by alexandra-bucur

Signed-off-by: Alexandra Bucur <alexandra-nona.bucur@ing.com>

## Description

Add now as date value for effective time in Asset Lineage and Asset Catalog handlers.

## Testing

JUnits

2022-08-22 11:14 UTC, popa-raluca approved these changes

2022-09-05 07:51 UTC, bogdan-sava requested changes
LocalDateTime instead of LocalDate ?

2022-09-26 12:23 UTC, alexandra-bucur commented
> LocalDateTime instead of LocalDate ?

After we discussed, we decided that what was missing was the time and I changed the ClockService to include it too.

2022-09-26 13:21 UTC, bogdan-sava approved these changes

2022-09-26 13:21 UTC, merged