Feature/initial omag server
odpi/egeria pull request #7782
Opened 2023-07-13 10:11 UTC by tijanapavicic

Initial setup with whitelisting health actuator endpoints, and basic unit test coverage for OMAGServer class.

## Related Issue(s)

## Testing

## Release Notes & Documentation

## Additional notes

2023-07-17 07:16 UTC, lpalashevski requested changes

2023-07-17 14:35 UTC, tijanapavicic commented on open-metadata-implementation/server-chassis/server-chassis-spring/src/main/resources/application.properties
> +spring.application.name=EgeriaServerChasisi
I believe that you are right, config is removed now.

2023-07-17 14:36 UTC, tijanapavicic commented on open-metadata-implementation/server-chassis/server-chassis-spring/src/main/java/org/odpi/openmetadata/server/OMAGServer.java
> +    public static final String OMAG_SERVER = "[omag-server]-";
Adjusted to audit log format.

2023-07-17 14:37 UTC, tijanapavicic commented on open-metadata-implementation/server-chassis/server-chassis-spring/src/main/java/org/odpi/openmetadata/server/config/AvailabilityProbesAutoConfiguration.java
> +    static class ProbesCondition extends SpringBootCondition {
Not needed for now at all. I have removed it for the time being.

2023-07-18 07:58 UTC, lpalashevski approved these changes

2023-07-18 09:02 UTC, merged